server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.107.170.133:3306/redis?characterEncoding=UTF-8&rewriteBatchedStatements=true&generateSimpleParameterMetadata=true
    username: jamie
    password: U7Vdax1bWrtDyEUry5u0ZISkC1ZRTWXFaAZqYVeYSM+GUo2GlPj0MnARtfcxRl6viIjwA+aTcmWsus09P23STQ==
    publicKey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAJZ5HV4uKwmXSeDks6f3S0OTPY7Kpo6Dfzhq7GL96s9CBJ9Y2BEi86dzW8HKgABGLTPdKtFApfB/m/pZWQjqnoUCAwEAAQ==
#    使用 druid 数据源
    type: com.alibaba.druid.pool.DruidDataSource
    # 初始化大小 最大,最小
    maxActive: 20
    initialSize: 5
    minIdle: 5
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,config
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000;config.decrypt=true;config.decrypt.key=${spring.datasource.publicKey};


## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  # #注意：一定要对应mapper映射xml文件的所在路径
  mapper-locations: classpath:/mappers/*.xml
  # 注意 对应实体的路径
  type-aliases-package: com.makesailing.neo.domain

#  分页插件

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

